// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67vwuXNxBRHZWdMZMmvl-nHYyUI6VfRk',
    appId: '1:981232366558:web:5514d63bc8e4586def234f',
    messagingSenderId: '981232366558',
    projectId: 'divine-dialogue-cb2ac',
    authDomain: 'divine-dialogue-cb2ac.firebaseapp.com',
    storageBucket: 'divine-dialogue-cb2ac.firebasestorage.app',
    measurementId: 'G-HRCDH1J1K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtrpREjddOUpaQkzYkBOstmec7M-X4Mnk',
    appId: '1:981232366558:android:b103be63f413b82cef234f',
    messagingSenderId: '981232366558',
    projectId: 'divine-dialogue-cb2ac',
    storageBucket: 'divine-dialogue-cb2ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyHGKxpnukEZPNMAmYrRBCMendbX2L9dM',
    appId: '1:981232366558:ios:9b55d714b406c50fef234f',
    messagingSenderId: '981232366558',
    projectId: 'divine-dialogue-cb2ac',
    storageBucket: 'divine-dialogue-cb2ac.firebasestorage.app',
    iosClientId: '981232366558-km1qv8tk7su16td6tnef4bggl0mbgu8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.divineDialogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyHGKxpnukEZPNMAmYrRBCMendbX2L9dM',
    appId: '1:981232366558:ios:9b55d714b406c50fef234f',
    messagingSenderId: '981232366558',
    projectId: 'divine-dialogue-cb2ac',
    storageBucket: 'divine-dialogue-cb2ac.firebasestorage.app',
    iosClientId: '981232366558-km1qv8tk7su16td6tnef4bggl0mbgu8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.divineDialogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA67vwuXNxBRHZWdMZMmvl-nHYyUI6VfRk',
    appId: '1:981232366558:web:85e8bca86faf0700ef234f',
    messagingSenderId: '981232366558',
    projectId: 'divine-dialogue-cb2ac',
    authDomain: 'divine-dialogue-cb2ac.firebaseapp.com',
    storageBucket: 'divine-dialogue-cb2ac.firebasestorage.app',
    measurementId: 'G-07M83FRPYN',
  );

}